# Generated by Django 4.2.4 on 2023-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_cents',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
