# Generated by Django 4.2.4 on 2023-08-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_price_cents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release_year',
        ),
    ]
