# Generated by Django 4.2.4 on 2023-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_book_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='ethnicity',
            field=models.CharField(default='Unknown', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='job',
            field=models.CharField(choices=[('AU', 'Author'), ('GH', 'Ghostwriter'), ('TR', 'Translator'), ('RE', 'Researches'), ('IL', 'Illustrator')], max_length=2, null=True),
        ),
    ]
