# Generated by Django 4.2.4 on 2023-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_author_born_author_ethnicity_author_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
