# Generated by Django 4.2.4 on 2023-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='job',
            field=models.CharField(choices=[('AU', 'Author'), ('GH', 'Ghostwriter'), ('TR', 'Translator'), ('RE', 'Researcher'), ('IL', 'Illustrator')], default='AU', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
