# Generated by Django 4.2.4 on 2023-08-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='private_download_url',
            field=models.CharField(default='books/test.pdf', max_length=255),
        ),
    ]
