# Generated by Django 4.2.4 on 2023-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_private_download_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_cents', models.PositiveIntegerField()),
                ('items', models.ManyToManyField(to='store.book')),
            ],
        ),
    ]
